# Generated by Django 5.1.6 on 2025-02-19 08:07

import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('artist', models.CharField(max_length=100, verbose_name='艺术家')),
                ('album', models.CharField(max_length=100, verbose_name='专辑')),
                ('release_date', models.DateField(verbose_name='发行日期')),
                ('audio_file', models.FileField(upload_to='music/', verbose_name='音频文件')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='歌曲封面')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='歌词')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.music', verbose_name='关联音乐')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=None, default='avatars/default.png', force_format=None, keep_meta=True, quality=85, scale=None, size=[200, 200], upload_to='avatars/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='头像')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='所在地')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
