# Generated by Django 5.1.6 on 2025-02-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
    ]
