# Generated by Django 5.1.6 on 2025-03-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20250228_1929'),
    ]

    operations = [
    ]
