# Generated by Django 5.1.7 on 2025-03-26 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20250303_1347'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_time', models.DateTimeField(auto_now_add=True, verbose_name='下载时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='music.music', verbose_name='下载音乐')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_downloads', to=settings.AUTH_USER_MODEL, verbose_name='下载用户')),
            ],
            options={
                'verbose_name': '下载记录',
                'verbose_name_plural': '下载记录管理',
                'ordering': ['-download_time'],
            },
        ),
    ]
