# Generated by Django 5.1.7 on 2025-03-31 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_profile_options_profile_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='常见问题')),
                ('answer', models.TextField(verbose_name='回答内容')),
                ('keywords', models.CharField(blank=True, help_text='多个关键词用逗号分隔', max_length=200, verbose_name='关键词')),
                ('category', models.CharField(choices=[('account', '账号相关'), ('music', '音乐相关'), ('website', '网站功能'), ('other', '其他')], default='other', max_length=50, verbose_name='分类')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '常见问答',
                'verbose_name_plural': '常见问答管理',
                'ordering': ['category', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UnknownQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='问题内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已解决')),
                ('suggested_answer', models.TextField(blank=True, null=True, verbose_name='建议回答')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_queries', to=settings.AUTH_USER_MODEL, verbose_name='解决人')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='提问用户')),
            ],
            options={
                'verbose_name': '未解决问题',
                'verbose_name_plural': '未解决问题管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
